'use client';

import './global.css';

import Navbar from '../components/navbar/navbar';
import { ThemeProvider } from 'next-themes';

const metadata = {
  title: 'Welcome to blog',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navItems = ['About', 'Blog'];

  return (
    <html lang="en">
      <body>
        <ThemeProvider
          enableSystem={true}
          attribute="class"
          disableTransitionOnChange
        >
          <Navbar navItems={navItems} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
